#!/bin/bash


# submit using hddm_submit 0 1 2 ...
# where each model number should correspond to a name in hddm_fit.py

# clear the params file a the start
: > params_hddm

# now write a file with all the models and trace_idx
for md in "$@"
do
	for i in {0..14}
	do
		for d in {1..60}
		do
  			echo "$md" "$i" "$d" >> params_hddm
  		done
	done
done

# add to stopos
module load pre2019
module load stopos
stopos create -p pool_persj
stopos add params_hddm -p pool_persj

# submit as many jobs as necessary
n=$(< params_hddm wc -l)
n=$((n / 15))

# n=$(($#))
echo 'number of jobs to submit: ' $n
sbatch --array=1-"$n" hddm_lisajob_persj

# show the status of my queue
sleep 2
squeue -u aeurai
