#!/bin/bash

#SBATCH -t 5-00:00:00 # maximum 5 days on cartesius
#SBATCH -p normal #
#SBATCH -n 1
#SBATCH -o /home/aeurai/jobs/slurm-%A_%a.out
#SBATCH -e /home/aeurai/jobs/slurm-%A_%a.err
#SBATCH --mail-user=a.e.urai@fsw.leidenuniv.nl # mail when done
#SBATCH --mail-type=END,FAIL # mail when done

# load necessary modules
module load Stopos/0.93-GCC-10.3.0
source activate python27 # use anaconda

# determine how many parallel jobs we can run on this node
ncores=`sara-get-num-cores`
((ncores -= 1)) # subtract one for system processes
echo "ncores = $ncores"

# loop over the cores available
for ((i=1; i<=ncores; i++)) ; do
(

  for ((j=1; j<=1; j++)) ; do
     stopos next -p pool
       if [ "$STOPOS_RC" != "OK" ]; then
        break
     fi
    echo "Running with parameters: $STOPOS_VALUE"

    # extract the input parameters
    # see https://userinfo.surfsara.nl/systems/lisa/software/stopos
    a=( $STOPOS_VALUE )
    m=${a[0]}
    i=${a[1]}
    d=${a[2]}

    # first, run the model
 	  eval "python /home/aeurai/code/MEG/hddm_fit.py -m $m -i $i -d $d"

    stopos remove -p pool
stopos status -p pool
   done
 ) &
done
wait

# echo "Job $PBS_JOBID finished at `date`" | mail $USER -s "Job $PBS_JOBID"

