#!/bin/bash

#SBATCH -t 5-00:00:00 # maximum 5 days on cartesius
#SBATCH -n 1
#SBATCH -o /home/aeurai/jobs/slurm-%A_%a.out
#SBATCH -e /home/aeurai/jobs/slurm-%A_%a.err
#SBATCH -p fat # run on fat nodes for enough memory
#SBATCH --mail-user=anne.urai@gmail.com # mail when done
#SBATCH --mail-type=END # mail when done

# load necessary modules
module load surf-devel
module load pre2019
module load stopos
module load mcr/r2016b # will get the default mcr version, 2018a after module update

# determine how many parallel jobs we can run on this node
ncores=`sara-get-num-cores`
((ncores -= 1)) # subtract one for system processes
ncores=15 # allow enough memory...
echo "ncores = $ncores"

# loop over the cores available
for ((i=1; i<=ncores; i++)) ; do
(

# set mcr cache to a unique value per processor, see email Lykle Voort 19.05.2016
export MCR_CACHE_ROOT=$TMPDIR/$i

  for ((j=1; j<=1; j++)) ; do
     stopos next -p pool
       if [ "$STOPOS_RC" != "OK" ]; then
        break
     fi
    echo "Running with parameters: $STOPOS_VALUE"
 	eval "/home/aeurai/code/MEG/stopos/dics_beamformer $STOPOS_VALUE"

    stopos remove -p pool
stopos status -p pool
   done
 ) &
done
wait

# clean the temporary files in scratch
rm -r "$TMPDIR"/*
echo "TMPDIR $TMPDIR emptied"